version: "3.3"
services:
    webmacquarie:
        build: .
        command: [sh, -c, "npm run build && npm run local"]
        volumes:
            - .:/usr/app/
            - /usr/app/node_modules
        networks:
            - web
        ports:
            - "3000:3000"
   networks:
    web: