version: "3.3"
services:
    nginx:
        image: nginx
        restart: always
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - web
        networks:
            - web
            - backend-database
    web:
        build: .
        command: npm run local
        depends_on:
            - database
        volumes:
            - .:/usr/app/
            - /usr/app/node_modules
        ports:
            - "3000:3000"
    database:
        container_name: database
        image: mongo # use latest official mongo version
        environment:
            - MONGO_INITDB_DATABASE=tacs-test
        ports:
            - '27017:27017'
        volumes:
            - ./mongodb_server_data:/data/db
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
        networks:
            - backend-database
networks:
    web:
    backend-database:
volumes:
    mongodb_server_data: